title: Ben Jennings
email: hello@benjennings.design
description: >-
  Personal portfolio site built with Jekyll.

permalink: pretty
baseurl: ""
url: "https://benjennings.design"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap

# exclude:
#   - README.md
#   - LICENSE.md
