title: Ben Jennings
email: hello@benjennings.design
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

permalink: pretty
baseurl: ""
url: "https://benjennings.design"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap

# exclude:
#   - README.md
#   - LICENSE.md
