title: Ben Jennings
email: hello@benjennings.design
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

permalink: pretty
baseurl: ""
url: "https://benjennings.design"

# Collections
collections:
  designs:
    output: true
    permalink: /designs/:name/
  experiments:
    output: true
    permalink: /experiments/:name/
  fundamentals:
    output: true
    permalink: /fundamentals/:name/
  resources:
    output: true
    permalink: /resources/:name/

# Default permalink structure
defaults:
  - scope:
      path: "_designs"
      type: "designs"
    values:
      layout: "none"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Include source files
include:
  - src

# Exclude build and config files
exclude:
  - config
  - node_modules
  - vendor
  - README.md
  - LICENSE.md

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap
