import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/YY1gZoLcBXAtiDy1LeDWW0/cards?node-id=36687-7139&t=RLhEgGTCEwbdnHNI-4",
  {
    props: {
      title: figma.string("Title"),
      icon: figma.string("Icon"),
      style: figma.enum("style", {
        brand: "brand",
        "accent-1": "accent-1",
        "accent-2": "accent-2",
        "accent-3": "accent-3",
      }),
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
      }),
    },
    example: (props) => html`<icon-card
        title=${props.title}
        icon=${props.icon}
        variant=${props.style}
      ></icon-card>`,
  },
)
