import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/YY1gZoLcBXAtiDy1LeDWW0/cards?node-id=36949-772&t=gV3v8sFwaREtbtlj-4",
  {
    props: {},
    example: (props) => html`<settings />`,
  },
)
