name: Take Webpage Screenshot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the webpage to screenshot'
        required: false
        default: 'https://example.com'

permissions:
  contents: write

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Create Screenshots Directory
        run: mkdir -p screenshots

      - name: Take Screenshot
        run: |
          node -e '
          const puppeteer = require("puppeteer");
          const fs = require("fs");
          (async () => {
            try {
              const browser = await puppeteer.launch({ args: ["--no-sandbox"] });
              const page = await browser.newPage();
              const url = process.env.INPUT_URL || "https://example.com";
              await page.goto(url, { waitUntil: "networkidle2" });
              const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
              const filepath = `screenshots/screenshot-${timestamp}.png`;
              await page.screenshot({ path: filepath });
              await browser.close();
              console.log("Screenshot saved to", filepath);
            } catch (error) {
              console.error("Error taking screenshot:", error);
              process.exit(1);
            }
          })();
          '

      - name: Commit Screenshot
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add new screenshot [skip ci]'
          file_pattern: screenshots/*.png